# Generated by Django 5.1.5 on 2025-04-02 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ReportsCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_month_year', models.DateField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Reports Calls',
                'ordering': ['-starting_month_year'],
            },
        ),
        migrations.CreateModel(
            name='ReportsEmails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metadata', models.JSONField(default=dict)),
                ('content', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Reports Emails',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportsVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_month_year', models.DateField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Reports Visits',
                'ordering': ['-starting_month_year'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('details', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('inProgress', 'In Progress'), ('done', 'Done')], default='todo', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneCallForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue', models.CharField(choices=[('counselling', 'Counselling'), ('business', 'Business'), ('general', 'General')], max_length=100)),
                ('callTransferredTo', models.CharField(choices=[('employee1', 'Employee 1'), ('employee2', 'Employee 2'), ('employee3', 'Employee 3')], max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='api.reportscalls')),
            ],
        ),
        migrations.CreateModel(
            name='InPersonVisitForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitPurpose', models.CharField(choices=[('counselling', 'Counselling'), ('business', 'Business'), ('general', 'General')], max_length=100)),
                ('taskTransferredTo', models.CharField(choices=[('employee1', 'Employee 1'), ('employee2', 'Employee 2'), ('employee3', 'Employee 3')], max_length=100)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('date', models.DateField()),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='api.reportsvisits')),
            ],
        ),
    ]
