# Generated by Django 5.1.5 on 2025-02-19 05:26

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InPersonVisitForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visitPurpose",
                    models.CharField(
                        choices=[
                            ("counselling", "Counselling"),
                            ("business", "Business"),
                            ("general", "General"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "taskTransferredTo",
                    models.CharField(
                        choices=[
                            ("employee1", "Employee 1"),
                            ("employee2", "Employee 2"),
                            ("employee3", "Employee 3"),
                        ],
                        max_length=100,
                    ),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("notes", models.TextField(blank=True)),
                ("date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="PhoneCallForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "issue",
                    models.CharField(
                        choices=[
                            ("counselling", "Counselling"),
                            ("business", "Business"),
                            ("general", "General"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "callTransferredTo",
                    models.CharField(
                        choices=[
                            ("employee1", "Employee 1"),
                            ("employee2", "Employee 2"),
                            ("employee3", "Employee 3"),
                        ],
                        max_length=100,
                    ),
                ),
                ("firstName", models.CharField(max_length=100)),
                ("lastName", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("notes", models.TextField(blank=True)),
                ("date", models.DateField()),
            ],
        ),
    ]
