# Generated by Django 5.1.5 on 2025-03-13 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsCalls',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_month_year', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Reports Calls',
                'ordering': ['starting_month_year'],
            },
        ),
        migrations.AddField(
            model_name='phonecallform',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.reportscalls'),
        ),
    ]
