# Generated by Django 5.1.5 on 2025-03-13 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_reportscalls_phonecallform_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonecallform',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.reportscalls'),
        ),
        migrations.AlterField(
            model_name='reportscalls',
            name='starting_month_year',
            field=models.DateField(editable=False),
        ),
    ]
