# Generated by Django 5.1.5 on 2025-03-26 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_phonecallform_report_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsVisits',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_month_year', models.DateField(editable=False)),
            ],
            options={
                'verbose_name_plural': 'Reports Visits',
                'ordering': ['-starting_month_year'],
            },
        ),
        migrations.AlterModelOptions(
            name='reportscalls',
            options={'ordering': ['-starting_month_year'], 'verbose_name_plural': 'Reports Calls'},
        ),
        migrations.AlterField(
            model_name='phonecallform',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='api.reportscalls'),
        ),
    ]
