# Generated by Django 5.1.5 on 2025-03-26 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_reportsvisits_alter_reportscalls_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inpersonvisitform',
            name='report',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms', to='api.reportsvisits'),
        ),
    ]
